In [10]:
import pandas as pd
import numpy as np
import sqlite3
from datetime import datetime
from plyer import notification 
import requests

# Extração tabela bancos

In [27]:
import functions as f

In [28]:
bancos = f.get_url("https://brasilapi.com.br/api/banks/v1")

In [29]:
bancos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      359 non-null    object
 1   name      357 non-null    object
 2   code      348 non-null    float64
 3   fullName  357 non-null    object
dtypes: float64(1), object(3)
memory usage: 11.3+ KB

In [30]:
bancos[bancos['name'].isnull()]

    ispb name  code fullName
357       NaN   NaN      NaN
358       NaN   NaN      NaN

In [31]:
bancos=bancos.dropna(subset='name')

In [32]:
bancos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      357 non-null    object
 1   name      357 non-null    object
 2   code      348 non-null    float64
 3   fullName  357 non-null    object
dtypes: float64(1), object(3)
memory usage: 13.9+ KB

In [13]:
bancos[bancos['code'].isnull()]

,ispb,name,code,fullName
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
10,00394460,STN,NaN,Secretaria do Tesouro Nacional - STN
40,02992335,CIP SA Siloc,NaN,CIP S.A
58,04391007,CAMARA INTERBANCARIA DE PAGAMENTOS - CIP,NaN,CIP S.A
184,28719664,Balcão B3,NaN,Sistema do Balcão B3
185,29011780,CIP SA C3,NaN,CIP S.A
285,54641030,Câmara B3,NaN,Câmara B3
304,60934221,Câmbio B3,NaN,Câmara de Câmbio B3

In [33]:
bancos.fillna(0, inplace = True)
bancos

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
2,00038121,Selic,0.0,Banco Central do Brasil - Selic
3,00038166,Bacen,0.0,Banco Central do Brasil
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."
...,...,...,...,...
352,92856905,ADVANCED CC LTDA,117.0,ADVANCED CORRETORA DE CÂMBIO LTDA
353,92874270,BCO DIGIMAIS S.A.,654.0,BANCO DIGIMAIS S.A.
354,92875780,WARREN CVMC LTDA,371.0,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...
355,92894922,BANCO ORIGINAL,212.0,Banco Original S.A.
356,94968518,EFX CC LTDA.,289.0,EFX CORRETORA DE CÂMBIO LTDA.

In [34]:
bancos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ispb      357 non-null    object
 1   name      357 non-null    object
 2   code      357 non-null    float64
 3   fullName  357 non-null    object
dtypes: float64(1), object(3)
memory usage: 13.9+ KB

# Extração tabela Pix

In [51]:
pix = f.get_url("https://brasilapi.com.br/api/pix/v1/participants/")
pix

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z
...,...,...,...,...,...,...
829,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03T09:30:00.000Z
830,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03T09:30:00.000Z
831,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03T09:30:00.000Z
832,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04T12:53:10.567Z
833,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03T09:30:00.000Z

In [52]:
pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ispb                     834 non-null    object
 1   nome                     834 non-null    object
 2   nome_reduzido            834 non-null    object
 3   modalidade_participacao  834 non-null    object
 4   tipo_participacao        834 non-null    object
 5   inicio_operacao          834 non-null    object
dtypes: object(6)
memory usage: 39.2+ KB

In [53]:
pix['inicio_operacao'] = pd.to_datetime(pix['inicio_operacao'])
pix['inicio_operacao'] = pix["inicio_operacao"].dt.strftime('%d/%m/%Y')

In [54]:
pix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ispb                     834 non-null    object
 1   nome                     834 non-null    object
 2   nome_reduzido            834 non-null    object
 3   modalidade_participacao  834 non-null    object
 4   tipo_participacao        834 non-null    object
 5   inicio_operacao          834 non-null    object
dtypes: object(6)
memory usage: 39.2+ KB

In [55]:
pix

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,03/11/2020
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,03/11/2020
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,03/11/2020
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,03/11/2020
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,03/11/2020
...,...,...,...,...,...,...
829,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,03/11/2020
830,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,03/11/2020
831,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,03/11/2020
832,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,04/10/2021
833,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,03/11/2020

# Extração Tabela corretoras

In [56]:
corretoras = f.get_url("https://brasilapi.com.br/api/cvm/corretoras/v1")

In [59]:
corretoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cnpj                      374 non-null    object
 1   type                      374 non-null    object
 2   nome_social               374 non-null    object
 3   nome_comercial            374 non-null    object
 4   status                    374 non-null    object
 5   email                     374 non-null    object
 6   telefone                  374 non-null    object
 7   cep                       374 non-null    object
 8   pais                      374 non-null    object
 9   uf                        374 non-null    object
 10  municipio                 374 non-null    object
 11  bairro                    374 non-null    object
 12  complemento               374 non-null    object
 13  logradouro                374 non-null    object
 14  data_patrimonio_liquido   374 non-null    object
 15  valor_patrimonio_liquido  374 non-null    object
 16  codigo_cvm                374 non-null    object
 17  data_inicio_situacao      374 non-null    object
 18  data_registro             374 non-null    object
dtypes: object(19)
memory usage: 55.6+ KB

In [60]:
corretoras

,cnpj,type,nome_social,nome_comercial,status,email,telefone,cep,pais,uf,municipio,bairro,complemento,logradouro,data_patrimonio_liquido,valor_patrimonio_liquido,codigo_cvm,data_inicio_situacao,data_registro
0,76621457000185,CORRETORAS,4UM DTVM S.A.,4UM INVESTIMENTOS,CANCELADA,controle@4um.com.br,33519966,80420210,BRASIL,PR,CURITIBA,CENTRO,4º ANDAR,R. VISCONDE DO RIO BRANCO 1488,2005-12-31,4228660.18,2275,2006-10-05,1968-01-15
1,33817677000176,CORRETORAS,ABC BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES ...,ABC BRASIL DTVM,CANCELADA,complianceregulatorio@abcbrasil.com.br,31702172,1453000,,SP,SÃO PAULO,ITAIM BIBI,2º ANDAR,"AV. CIDADE JARDIM, 803",2002-12-31,0.00,3514,2002-10-14,2002-10-14
2,10664027000132,CORRETORAS,ABERTURA CCVM LTDA,ABERTURA CCVM LTDA,CANCELADA,,,50010240,BRASIL,PE,RECIFE,,,R DO IMP.D.PEDRO II 239/CJ.102,1989-12-31,5995252.29,329,1990-06-12,1986-07-08
3,44527444000155,CORRETORAS,ABN AMRO CLEARING CORRETORA DE T-TULOS E VALOR...,,EM FUNCIONAMENTO NORMAL,canal.comunicacao@br.abnamro.com,30737417,4551010,,SP,SÃO PAULO,VILA OLIMPIA,"11¦ ANDAR, CJ. 111","RUA FIDÛNCIO RAMOS, N¦ 302, TORRE B",2023-12-31,11122779.75,3794,2022-06-20,2022-06-20
4,33819590000138,CORRETORAS,AÇÃO S.A. CORRETORA DE VALORES E CÂMBIO,ACAO SA CVC,CANCELADA,,5095755,20040040,BRASIL,RJ,RIO DE JANEIRO,CENTRO,,"PRAÇA OLAVO BILAC, 28/ SL. 608",2000-12-31,291862.38,1112,2001-04-11,1968-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,01170892000131,CORRETORAS,VOTORANTIM CTVM LTDA,VOTORANTIM,CANCELADA,demandasregulatorias@bancovotorantim.com.br,51711894,4794000,BRASIL,SP,SÃO PAULO,VL.GERTRUDES,TORRE A-14º ANDAR,"AV DAS NAÇÕES UNIDAS, 14.171",2017-12-31,266791832.77,3166,2018-08-27,1996-03-15
370,61769790000169,CORRETORAS,WALPIRES S/A CCTVM,WALPIRES S/A CCTVM,CANCELADA,andre@walpires.com.br,28087065,1452002,BRASIL,SP,SÃO PAULO,JARDIM PAULISTANO,1309 - 9ºANDAR,AVENIDA BRIGADEIRO FARIA LIMA,2017-12-31,7464373.90,1902,2019-09-24,1967-09-20
371,92875780000131,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,WARREN CORRETORA,EM FUNCIONAMENTO NORMAL,juridico@warren.com.br,32372273,90035191,,RS,PORTO ALEGRE,BOM FIM,2º ANDAR,"AVENIDA OSVALDO ARANHA, 720",2023-12-31,20672910.31,2534,1967-12-06,1967-12-06
372,24543688000114,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,PERFIL,CANCELADA,,2249022,52061540,BRASIL,PE,RECIFE,CASA FORTE,,"AV.17 DE AGOSTO,2579",1996-12-31,608260.02,2658,1997-02-21,1989-11-14
373,02332886000104,CORRETORAS,XP INVESTIMENTOS CCTVM S.A.,XP INVESTIMENTOS,EM FUNCIONAMENTO NORMAL,fabricio.almeida@xpi.com.br,30272237,22440032,,RJ,RIO DE JANEIRO,LEBLON,5º ANDAR,AVENIDA ATAULFO DE PAIVA 153,2023-12-31,8405739266.66,3247,1998-02-10,1997-12-05